[wokwi]
version = 1
# Firmware MicroPython oficial com .bin e .elf obrigatórios
firmware = "firmware/ESP32_GENERIC-20240602-v1.23.0.bin"
elf = "firmware/ESP32_GENERIC-20240602-v1.23.0.elf"

# Configuração UART
[[wokwi.uart]]
port = 0
baud = 115200

# Configuração WiFi
[wokwi.wifi]
ssid = "Wokwi-GUEST"
password = ""

# Mapear seu script Python
[wokwi.files]
"src/micropython/main.py" = "/main.