[build]
target = "xtensa-esp32-none-elf"

[target.xtensa-esp32-none-elf]
linker = "ldproxy"
runner = "espflash flash --monitor"

[unstable]
build-std = ["std", "panic_abort"]

[env]
ESP_IDF_TOOLS_INSTALL_DIR = "global"
